name: kl1-wblca
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - plotly
  - pip
  - pip:
    - openturns
    - colorama
    - rich
    - roman
